name: Новая проблема
description: Новая проблема по шаблону из формы
title: "[Bug]: "
labels: ["bug"]
projects: ["Проект сайта", "Онлайн-магазин"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Заполните баг репорт
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Проект
      options:
        - Sprint manager
        - Онлайн магазин
        - Сайт компании
    validations:
      required: true        
  - type: dropdown
    id: component
    attributes:
      label: Компонент приложения
      description: В каком компоненте приложения найдена ошибка
      options:
        - Окно регистрации на сайте
        - Форма логина
        - Другое
    validations:
      required: true 
  - type: dropdown
    id: version
    attributes:
      label: Версия
      description: Номер версии
      options:
        - 1.0
        - 1.1
        - 2.0
      default: 0
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Критичность
      description: Критичность проблемы
      options:
        - Блокирующая
        - Неблокирующая
      default: 0
    validations:
      required: true   
  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      description: Приоритет проблемы
      options:
        - Низкий
        - Средний
        - Высокий
      default: 0
    validations:
      required: true        
  - type: dropdown
    id: operating_systems
    attributes:
      label: В какой операционной системе вы увидели проблему
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Windows 8 or earlier
        - Linux    
        - Mac OS X 14 (Somona)  
        - Mac OS X 13 or earlier  
  - type: dropdown
    id: browsers
    attributes:
      label: В каком браузере вы увидели проблему
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge     
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Шаги воспроизведения
      description: Опишите как воспроизвести проблему 
      render: shell
  - type: textarea
    id: current_result
    attributes:
      label: Полученный результат
      description: Опишите какой результат получается сейчас 
      render: shell
  - type: textarea
    id: expected_result
    attributes:
      label: Ожидаемый результат
      description: Опишите какой результат ожидается 
      render: shell
