name: Новая проблема
description: Новая проблема по шаблону из формы
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["Проект сайта", "Онлайн-магазин"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Заполните баг репорт
  - type: dropdown
     id: project
     attributes:
      label: Project
      description: Проект
      options:
        - Онлайн магазин
        - Сайт компании
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Номер версии
      options:
        - 1.0
        - 1.1
        - 2.0
      default: 1.0
    validations:
      required: true
  - type: dropdown
    id: operating_systems
    attributes:
      label: В какой операционной системе вы увидели проблему
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Windows 8 or earlier
        - Linux    
        - Mac OS X 14 (Somona)  
        - Mac OS X 13 or earlier  
  - type: dropdown
    id: browsers
    attributes:
      label: В каком браузере вы увидели проблему
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge     
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Шаги воспроизведения
      description: Опишите как воспроизвести проблему 
      render: shell
  - type: textarea
    id: current_result
    attributes:
      label: Полученный результат
      description: Опишите какой результат получается сейчас 
      render: shell
  - type: textarea
    id: expected_result
    attributes:
      label: Ожидаемый результат
      description: Опишите какой результат ожидается 
      render: shell
